# Version of docker-compose
version: '3'

# Containers we are going to run
services:
  # Our Phoenix container
  phoenix-slim:
    # The build parameters for this container. Current directory
    build: .
    container_name: phoenix-slim
    environment:
      # Variables to connect to our Postgres server
      PGHOST: db
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: hellodb
      PGPORT: 5432
      # Hostname of our Postgres container
      PGHOST: db
    ports:
      # Mapping the port to make the Phoenix app accessible outside of the container
      - "4000:4000"
    depends_on:
      # The db container needs to be started before we start this container
      - db
    volumes:
      # The mapped directory from host to container
      - ./src:/app
  db:
    # We use the predefined Postgres image
    image: postgres:9.6
    container_name: db
    ports:
      - "5432:5432"
    environment:
      # Set user/password for Postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      # Set a path where Postgres should store the data
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data
# Define the volumes
# volumes:
#   pgdata:
